spring.datasource.url=jdbc:postgresql://localhost:5432/codecollab
spring.datasource.username=postgres
spring.datasource.password=postgress@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.redis.host=localhost
spring.redis.port=6379

server.port=8080

jwt.secret=codecollab-super-secret-key-12345678901234
jwt.expiration=86400000