version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: codecollab-postgres
    environment:
      POSTGRES_DB: codecollab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: codecollab-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: codecollab-backend
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"